/**
* FlexCN Northbound API
* This API allows xApps to communicate with FlexCN. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * FlowProfile.h
 *
 * 
 */

#ifndef FlowProfile_H_
#define FlowProfile_H_


#include <string>
#include <nlohmann/json.hpp>

namespace flexcn
{

/// <summary>
/// 
/// </summary>
class  FlowProfile
{
public:
    FlowProfile();
    virtual ~FlowProfile() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    // Helper overload for validate. Used when one model stores another model and calls it's validate.
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const FlowProfile& rhs) const;
    bool operator!=(const FlowProfile& rhs) const;

    /////////////////////////////////////////////
    /// FlowProfile members

    /// <summary>
    /// 
    /// </summary>
    std::string getAnAddr() const;
    void setAnAddr(std::string const& value);
    bool anAddrIsSet() const;
    void unsetAn_addr();
    /// <summary>
    /// 
    /// </summary>
    std::string getUpfAddr() const;
    void setUpfAddr(std::string const& value);
    bool upfAddrIsSet() const;
    void unsetUpf_addr();
    /// <summary>
    /// 
    /// </summary>
    int32_t getQfi() const;
    void setQfi(int32_t const value);
    bool qfiIsSet() const;
    void unsetQfi();

    friend void to_json(nlohmann::json& j, const FlowProfile& o);
    friend void from_json(const nlohmann::json& j, FlowProfile& o);
protected:
    std::string m_An_addr;
    bool m_An_addrIsSet;
    std::string m_Upf_addr;
    bool m_Upf_addrIsSet;
    int32_t m_Qfi;
    bool m_QfiIsSet;

    
};

} // namespace org::openapitools::server::model

#endif /* FlowProfile_H_ */
