/**
* FlexCN Northbound API
* This API allows xApps to communicate with FlexCN. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * StatPerUE.h
 *
 * 
 */

#ifndef StatPerUE_H_
#define StatPerUE_H_


#include <string>
#include "Event.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace flexcn_server {
namespace model {

/// <summary>
/// 
/// </summary>
class  StatPerUE
{
public:
    StatPerUE();
    virtual ~StatPerUE() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    bool operator==(const StatPerUE& rhs) const;
    bool operator!=(const StatPerUE& rhs) const;

    /////////////////////////////////////////////
    /// StatPerUE members

    /// <summary>
    /// a short form unique determine id of ue and 4g/5g services it is using.
    /// </summary>
    std::string getId() const;
    void setId(std::string const& value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    Event getEvent() const;
    void setEvent(Event const& value);
    bool eventIsSet() const;
    void unsetEvent();

    friend void to_json(nlohmann::json& j, const StatPerUE& o);
    friend void from_json(const nlohmann::json& j, StatPerUE& o);
protected:
    std::string m_Id;
    bool m_IdIsSet;
    Event m_Event;
    bool m_EventIsSet;

    // Helper overload for validate. Used when one model stores another model and calls it's validate.
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace model
}  // namespace flexcn_server
}  // namespace oai
#endif /* StatPerUE_H_ */
